version: '3.8'

services:
  app:
    image: app
    build:
      context: ./app
      dockerfile: Dockerfile
    # depends_on:
    #   - redis
    volumes:
      - ./app/app:/app/app
    # of the app container`CMD`To overwrite`command`use
    command: "uvicorn app.main:app --reload --host 0.0.0.0"
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - nginx_network
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    # depends_on:
    #   # `app`Because the service (container) needs to be started first`depends_on`Is specified
    #   - app
    volumes:
      # volume mount:"Host OS path:Path in the container"
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - nginx_network
  redis:
    image: redis:alpine
    restart: always
    command: redis-server --port 6379
    container_name: redis
    volumes:
      - ./data/redis/data:/data
      - ./data/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf.custom
      - ./data/redis/acl/users.acl:/etc/redis/users.acl
    command: redis-server /usr/local/etc/redis/redis.conf.custom
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
    networks:
      - nginx_network
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
    nginx_network:
        driver: bridge
