[tool.poetry]
name = "vagazine_app"
version = "0.1.0"
description = "vagazine"
authors = ["direcision <direcision@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "*"
fastapi = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"